{{- if and .Values.s3.enabled (eq .Values.s3.provider "gcp") }}
apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: {{ include "platform.name" . }}-{{ .Values.s3.bucketName }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  location: {{ .Values.s3.gcp.location }}
  storageClass: {{ .Values.s3.gcp.storageClass }}
  providerConfigRef:
    name: {{ .Values.s3.gcp.providerConfigRef }}
{{- end }}
