apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: hiroba-location
  title: hiroba-location
  description: Collection of all Backstage templates
  annotations:
    backstage.io/techdocs-ref: dir:./docs
spec:
  targets:
    - ./templates/app-template/template.yaml
    - ./templates/stack-template/template.yaml
