apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: prometheus-platform
  annotations:
    meta.crossplane.io/maintainer: platform-team@yourcompany.com
    meta.crossplane.io/source: github.com/yourcompany/platform-engineering
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Self-service Prometheus instances with alerting and federation.
spec:
  crossplane:
    version: ">=v2.0.0"
  dependsOn:
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.2.0"
