// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * GrafanaDatasource is the Schema for the grafanadatasources API
 *
 * @schema GrafanaDatasource
 */
export class GrafanaDatasource extends ApiObject {
  /**
   * Returns the apiVersion and kind for "GrafanaDatasource"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'grafana.integreatly.org/v1beta1',
    kind: 'GrafanaDatasource',
  }

  /**
   * Renders a Kubernetes manifest for "GrafanaDatasource".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: GrafanaDatasourceProps): any {
    return {
      ...GrafanaDatasource.GVK,
      ...toJson_GrafanaDatasourceProps(props),
    };
  }

  /**
   * Defines a "GrafanaDatasource" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: GrafanaDatasourceProps) {
    super(scope, id, {
      ...GrafanaDatasource.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...GrafanaDatasource.GVK,
      ...toJson_GrafanaDatasourceProps(resolved),
    };
  }
}

/**
 * GrafanaDatasource is the Schema for the grafanadatasources API
 *
 * @schema GrafanaDatasource
 */
export interface GrafanaDatasourceProps {
  /**
   * @schema GrafanaDatasource#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * GrafanaDatasourceSpec defines the desired state of GrafanaDatasource
   *
   * @schema GrafanaDatasource#spec
   */
  readonly spec: GrafanaDatasourceSpec;
}

/**
 * Converts an object of type 'GrafanaDatasourceProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GrafanaDatasourceProps(obj: GrafanaDatasourceProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_GrafanaDatasourceSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * GrafanaDatasourceSpec defines the desired state of GrafanaDatasource
 *
 * @schema GrafanaDatasourceSpec
 */
export interface GrafanaDatasourceSpec {
  /**
   * Allow the Operator to match this resource with Grafanas outside the current namespace
   *
   * @schema GrafanaDatasourceSpec#allowCrossNamespaceImport
   */
  readonly allowCrossNamespaceImport?: boolean;

  /**
   * @schema GrafanaDatasourceSpec#datasource
   */
  readonly datasource: GrafanaDatasourceSpecDatasource;

  /**
   * Selects Grafana instances for import
   *
   * @schema GrafanaDatasourceSpec#instanceSelector
   */
  readonly instanceSelector: GrafanaDatasourceSpecInstanceSelector;

  /**
   * plugins
   *
   * @schema GrafanaDatasourceSpec#plugins
   */
  readonly plugins?: GrafanaDatasourceSpecPlugins[];

  /**
   * How often the resource is synced, defaults to 10m0s if not set
   *
   * @schema GrafanaDatasourceSpec#resyncPeriod
   */
  readonly resyncPeriod?: string;

  /**
   * Suspend pauses synchronizing attempts and tells the operator to ignore changes
   *
   * @schema GrafanaDatasourceSpec#suspend
   */
  readonly suspend?: boolean;

  /**
   * The UID, for the datasource, fallback to the deprecated spec.datasource.uid
   * and metadata.uid. Can be any string consisting of alphanumeric characters,
   * - and _ with a maximum length of 40 +optional
   *
   * @schema GrafanaDatasourceSpec#uid
   */
  readonly uid?: string;

  /**
   * environments variables from secrets or config maps
   *
   * @schema GrafanaDatasourceSpec#valuesFrom
   */
  readonly valuesFrom?: GrafanaDatasourceSpecValuesFrom[];
}

/**
 * Converts an object of type 'GrafanaDatasourceSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GrafanaDatasourceSpec(obj: GrafanaDatasourceSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'allowCrossNamespaceImport': obj.allowCrossNamespaceImport,
    'datasource': toJson_GrafanaDatasourceSpecDatasource(obj.datasource),
    'instanceSelector': toJson_GrafanaDatasourceSpecInstanceSelector(obj.instanceSelector),
    'plugins': obj.plugins?.map(y => toJson_GrafanaDatasourceSpecPlugins(y)),
    'resyncPeriod': obj.resyncPeriod,
    'suspend': obj.suspend,
    'uid': obj.uid,
    'valuesFrom': obj.valuesFrom?.map(y => toJson_GrafanaDatasourceSpecValuesFrom(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema GrafanaDatasourceSpecDatasource
 */
export interface GrafanaDatasourceSpecDatasource {
  /**
   * @schema GrafanaDatasourceSpecDatasource#access
   */
  readonly access?: string;

  /**
   * @schema GrafanaDatasourceSpecDatasource#basicAuth
   */
  readonly basicAuth?: boolean;

  /**
   * @schema GrafanaDatasourceSpecDatasource#basicAuthUser
   */
  readonly basicAuthUser?: string;

  /**
   * @schema GrafanaDatasourceSpecDatasource#database
   */
  readonly database?: string;

  /**
   * Whether to enable/disable editing of the datasource in Grafana UI
   *
   * @schema GrafanaDatasourceSpecDatasource#editable
   */
  readonly editable?: boolean;

  /**
   * @schema GrafanaDatasourceSpecDatasource#isDefault
   */
  readonly isDefault?: boolean;

  /**
   * @schema GrafanaDatasourceSpecDatasource#jsonData
   */
  readonly jsonData?: any;

  /**
   * @schema GrafanaDatasourceSpecDatasource#name
   */
  readonly name?: string;

  /**
   * Deprecated field, it has no effect
   *
   * @schema GrafanaDatasourceSpecDatasource#orgId
   */
  readonly orgId?: number;

  /**
   * @schema GrafanaDatasourceSpecDatasource#secureJsonData
   */
  readonly secureJsonData?: any;

  /**
   * @schema GrafanaDatasourceSpecDatasource#type
   */
  readonly type?: string;

  /**
   * Deprecated field, use spec.uid instead
   *
   * @schema GrafanaDatasourceSpecDatasource#uid
   */
  readonly uid?: string;

  /**
   * @schema GrafanaDatasourceSpecDatasource#url
   */
  readonly url?: string;

  /**
   * @schema GrafanaDatasourceSpecDatasource#user
   */
  readonly user?: string;
}

/**
 * Converts an object of type 'GrafanaDatasourceSpecDatasource' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GrafanaDatasourceSpecDatasource(obj: GrafanaDatasourceSpecDatasource | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'access': obj.access,
    'basicAuth': obj.basicAuth,
    'basicAuthUser': obj.basicAuthUser,
    'database': obj.database,
    'editable': obj.editable,
    'isDefault': obj.isDefault,
    'jsonData': obj.jsonData,
    'name': obj.name,
    'orgId': obj.orgId,
    'secureJsonData': obj.secureJsonData,
    'type': obj.type,
    'uid': obj.uid,
    'url': obj.url,
    'user': obj.user,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Selects Grafana instances for import
 *
 * @schema GrafanaDatasourceSpecInstanceSelector
 */
export interface GrafanaDatasourceSpecInstanceSelector {
  /**
   * matchExpressions is a list of label selector requirements. The requirements are ANDed.
   *
   * @schema GrafanaDatasourceSpecInstanceSelector#matchExpressions
   */
  readonly matchExpressions?: GrafanaDatasourceSpecInstanceSelectorMatchExpressions[];

  /**
   * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
   * map is equivalent to an element of matchExpressions, whose key field is "key", the
   * operator is "In", and the values array contains only "value". The requirements are ANDed.
   *
   * @schema GrafanaDatasourceSpecInstanceSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };
}

/**
 * Converts an object of type 'GrafanaDatasourceSpecInstanceSelector' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GrafanaDatasourceSpecInstanceSelector(obj: GrafanaDatasourceSpecInstanceSelector | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'matchExpressions': obj.matchExpressions?.map(y => toJson_GrafanaDatasourceSpecInstanceSelectorMatchExpressions(y)),
    'matchLabels': ((obj.matchLabels) === undefined) ? undefined : (Object.entries(obj.matchLabels).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema GrafanaDatasourceSpecPlugins
 */
export interface GrafanaDatasourceSpecPlugins {
  /**
   * @schema GrafanaDatasourceSpecPlugins#name
   */
  readonly name: string;

  /**
   * @schema GrafanaDatasourceSpecPlugins#version
   */
  readonly version: string;
}

/**
 * Converts an object of type 'GrafanaDatasourceSpecPlugins' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GrafanaDatasourceSpecPlugins(obj: GrafanaDatasourceSpecPlugins | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'version': obj.version,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema GrafanaDatasourceSpecValuesFrom
 */
export interface GrafanaDatasourceSpecValuesFrom {
  /**
   * @schema GrafanaDatasourceSpecValuesFrom#targetPath
   */
  readonly targetPath: string;

  /**
   * @schema GrafanaDatasourceSpecValuesFrom#valueFrom
   */
  readonly valueFrom: GrafanaDatasourceSpecValuesFromValueFrom;
}

/**
 * Converts an object of type 'GrafanaDatasourceSpecValuesFrom' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GrafanaDatasourceSpecValuesFrom(obj: GrafanaDatasourceSpecValuesFrom | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'targetPath': obj.targetPath,
    'valueFrom': toJson_GrafanaDatasourceSpecValuesFromValueFrom(obj.valueFrom),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * A label selector requirement is a selector that contains values, a key, and an operator that
 * relates the key and values.
 *
 * @schema GrafanaDatasourceSpecInstanceSelectorMatchExpressions
 */
export interface GrafanaDatasourceSpecInstanceSelectorMatchExpressions {
  /**
   * key is the label key that the selector applies to.
   *
   * @schema GrafanaDatasourceSpecInstanceSelectorMatchExpressions#key
   */
  readonly key: string;

  /**
   * operator represents a key's relationship to a set of values.
   * Valid operators are In, NotIn, Exists and DoesNotExist.
   *
   * @schema GrafanaDatasourceSpecInstanceSelectorMatchExpressions#operator
   */
  readonly operator: string;

  /**
   * values is an array of string values. If the operator is In or NotIn,
   * the values array must be non-empty. If the operator is Exists or DoesNotExist,
   * the values array must be empty. This array is replaced during a strategic
   * merge patch.
   *
   * @schema GrafanaDatasourceSpecInstanceSelectorMatchExpressions#values
   */
  readonly values?: string[];
}

/**
 * Converts an object of type 'GrafanaDatasourceSpecInstanceSelectorMatchExpressions' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GrafanaDatasourceSpecInstanceSelectorMatchExpressions(obj: GrafanaDatasourceSpecInstanceSelectorMatchExpressions | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'operator': obj.operator,
    'values': obj.values?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema GrafanaDatasourceSpecValuesFromValueFrom
 */
export interface GrafanaDatasourceSpecValuesFromValueFrom {
  /**
   * Selects a key of a ConfigMap.
   *
   * @schema GrafanaDatasourceSpecValuesFromValueFrom#configMapKeyRef
   */
  readonly configMapKeyRef?: GrafanaDatasourceSpecValuesFromValueFromConfigMapKeyRef;

  /**
   * Selects a key of a Secret.
   *
   * @schema GrafanaDatasourceSpecValuesFromValueFrom#secretKeyRef
   */
  readonly secretKeyRef?: GrafanaDatasourceSpecValuesFromValueFromSecretKeyRef;
}

/**
 * Converts an object of type 'GrafanaDatasourceSpecValuesFromValueFrom' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GrafanaDatasourceSpecValuesFromValueFrom(obj: GrafanaDatasourceSpecValuesFromValueFrom | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'configMapKeyRef': toJson_GrafanaDatasourceSpecValuesFromValueFromConfigMapKeyRef(obj.configMapKeyRef),
    'secretKeyRef': toJson_GrafanaDatasourceSpecValuesFromValueFromSecretKeyRef(obj.secretKeyRef),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Selects a key of a ConfigMap.
 *
 * @schema GrafanaDatasourceSpecValuesFromValueFromConfigMapKeyRef
 */
export interface GrafanaDatasourceSpecValuesFromValueFromConfigMapKeyRef {
  /**
   * The key to select.
   *
   * @schema GrafanaDatasourceSpecValuesFromValueFromConfigMapKeyRef#key
   */
  readonly key: string;

  /**
   * Name of the referent.
   * This field is effectively required, but due to backwards compatibility is
   * allowed to be empty. Instances of this type with an empty value here are
   * almost certainly wrong.
   * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   *
   * @schema GrafanaDatasourceSpecValuesFromValueFromConfigMapKeyRef#name
   */
  readonly name?: string;

  /**
   * Specify whether the ConfigMap or its key must be defined
   *
   * @schema GrafanaDatasourceSpecValuesFromValueFromConfigMapKeyRef#optional
   */
  readonly optional?: boolean;
}

/**
 * Converts an object of type 'GrafanaDatasourceSpecValuesFromValueFromConfigMapKeyRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GrafanaDatasourceSpecValuesFromValueFromConfigMapKeyRef(obj: GrafanaDatasourceSpecValuesFromValueFromConfigMapKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Selects a key of a Secret.
 *
 * @schema GrafanaDatasourceSpecValuesFromValueFromSecretKeyRef
 */
export interface GrafanaDatasourceSpecValuesFromValueFromSecretKeyRef {
  /**
   * The key of the secret to select from.  Must be a valid secret key.
   *
   * @schema GrafanaDatasourceSpecValuesFromValueFromSecretKeyRef#key
   */
  readonly key: string;

  /**
   * Name of the referent.
   * This field is effectively required, but due to backwards compatibility is
   * allowed to be empty. Instances of this type with an empty value here are
   * almost certainly wrong.
   * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   *
   * @schema GrafanaDatasourceSpecValuesFromValueFromSecretKeyRef#name
   */
  readonly name?: string;

  /**
   * Specify whether the Secret or its key must be defined
   *
   * @schema GrafanaDatasourceSpecValuesFromValueFromSecretKeyRef#optional
   */
  readonly optional?: boolean;
}

/**
 * Converts an object of type 'GrafanaDatasourceSpecValuesFromValueFromSecretKeyRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GrafanaDatasourceSpecValuesFromValueFromSecretKeyRef(obj: GrafanaDatasourceSpecValuesFromValueFromSecretKeyRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'key': obj.key,
    'name': obj.name,
    'optional': obj.optional,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

