{{- if and .Values.postgres.enabled (eq .Values.postgres.provider "aws") }}
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: {{ include "platform.name" . }}-pg
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.postgres.aws.region }}
    dbInstanceClass: {{ .Values.postgres.aws.instanceClass }}
    allocatedStorage: {{ .Values.postgres.aws.allocatedStorage }}
    engine: {{ .Values.postgres.aws.engine }}
    engineVersion: {{ .Values.postgres.aws.engineVersion | quote }}
    masterUsername: {{ .Values.postgres.aws.masterUsername }}
    masterUserPasswordSecretRef:
      name: {{ .Values.postgres.aws.masterUserPasswordSecretRef.name }}
      namespace: {{ .Values.postgres.aws.masterUserPasswordSecretRef.namespace }}
      key: {{ .Values.postgres.aws.masterUserPasswordSecretRef.key }}
  providerConfigRef:
    name: {{ .Values.postgres.aws.providerConfigRef }}
  writeConnectionSecretToRef:
    name: {{ .Values.postgres.aws.writeConnectionSecretToRef.name }}
    namespace: {{ .Values.postgres.aws.writeConnectionSecretToRef.namespace }}
{{- end }}
