{{- if and .Values.postgres.enabled (eq .Values.postgres.provider "gcp") }}
apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: {{ include "platform.name" . }}-pg
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  forProvider:
    region: {{ .Values.postgres.gcp.region }}
    databaseVersion: {{ .Values.postgres.gcp.databaseVersion }}
    settings:
      tier: {{ .Values.postgres.gcp.tier }}
  providerConfigRef:
    name: {{ .Values.postgres.gcp.providerConfigRef }}
  writeConnectionSecretToRef:
    name: {{ .Values.postgres.gcp.writeConnectionSecretToRef.name }}
    namespace: {{ .Values.postgres.gcp.writeConnectionSecretToRef.namespace }}
{{- end }}
