name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
{%- raw %}
      docs--release_created: ${{ steps.release.outputs['docs--release_created'] }}
      docs--tag_name: ${{ steps.release.outputs['docs--tag_name'] }}
      docs--version: ${{ steps.release.outputs['docs--version'] }}
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-docs:
    needs: release-please
    if: needs.release-please.outputs.docs--release_created == 'true'
    uses: 7K-Hiroba/workflows-library/.github/workflows/release-docs.yml@v1
    with:
      path: docs
      version: ${{ needs.release-please.outputs.docs--version }}
    secrets: inherit
{% endraw %}
