// Code generated by scripts/gen-contract.ts from contract/contract.json. DO NOT EDIT.

package contract

const APIGroup = "platform.7kgroup.org"
const APIVersion = "v1alpha1"
const APIGroupVersion = "platform.7kgroup.org/v1alpha1"
const OrchestratorFunctionName = "function-platform"

const (
	LabelTeam       = "team"
	LabelCostCenter = "cost-center"
	LabelStack      = "platform.7kgroup.org/stack"
)

// ProfileDefaults holds the per-profile infrastructure defaults applied by
// handlers when the XR spec does not override them.
type ProfileDefaults struct {
	InstanceClass       string
	MultiAZ             bool
	BackupRetentionDays int64
	DeletionProtection  bool
	StorageEncrypted    bool
	DeletionPolicy      string
}

var Profiles = map[string]ProfileDefaults{
	"development": {InstanceClass: "db.t3.micro", MultiAZ: false, BackupRetentionDays: 1, DeletionProtection: false, StorageEncrypted: false, DeletionPolicy: "Delete"},
	"staging":     {InstanceClass: "db.t3.small", MultiAZ: false, BackupRetentionDays: 7, DeletionProtection: false, StorageEncrypted: true, DeletionPolicy: "Delete"},
	"production":  {InstanceClass: "db.r6g.xlarge", MultiAZ: true, BackupRetentionDays: 30, DeletionProtection: true, StorageEncrypted: true, DeletionPolicy: "Orphan"},
}

var ProfileNames = []string{"development", "staging", "production"}

var PostgresProviders = []string{"aws", "cnpg"}

const PostgresDefaultProvider = "cnpg"
const PostgresDefaultRegion = "us-east-1"

var PostgresConnectionKeys = []string{"host", "port", "username", "password", "database", "uri"}

var ObjectStorageProviders = []string{"s3", "garage"}

const ObjectStorageDefaultProvider = "garage"
const ObjectStorageDefaultRegion = "us-east-1"

var ObjectStorageConnectionKeys = []string{"endpoint", "bucket", "region", "accessKeyId", "secretAccessKey", "uri"}

// ProductByKind maps an XR kind to its contract product key.
var ProductByKind = map[string]string{
	"PostgresInstance": "postgres",
	"ObjectBucket":     "objectStorage",
}

// DefaultProviderByKind maps an XR kind to its contract default provider.
var DefaultProviderByKind = map[string]string{
	"PostgresInstance": "cnpg",
	"ObjectBucket":     "garage",
}

// Dependency is a CRD that must be installed before the given XR kind can be
// reconciled, plus an actionable install hint surfaced to the client.
type Dependency struct {
	CRD  string
	Hint string
}

// Dependencies maps XR kind -> provider ("*" = all providers) -> required CRDs.
var Dependencies = map[string]map[string][]Dependency{
	"PostgresInstance": {
		"cnpg": {{CRD: "clusters.postgresql.cnpg.io", Hint: "install the CloudNativePG operator: helm upgrade --install cnpg cnpg/cloudnative-pg -n cnpg-system --create-namespace"}},
		"aws":  {{CRD: "instances.rds.aws.m.upbound.io", Hint: "install provider-aws-rds: kubectl apply -f infrastructure/crossplane-control-plane/providers.yaml"}},
	},
	"ObjectBucket": {
		"garage": {{CRD: "garagebuckets.garage.rajsingh.info", Hint: "install the Garage operator (garage.rajsingh.info)"}},
		"s3":     {{CRD: "buckets.s3.aws.m.upbound.io", Hint: "install provider-aws-s3: kubectl apply -f infrastructure/crossplane-control-plane/providers.yaml"}},
	},
	"GrafanaInstance": {
		"*": {{CRD: "releases.helm.m.crossplane.io", Hint: "install provider-helm (Hiroba scripts/e2e-setup.sh) and a namespaced <team>-helm ProviderConfig (scripts/team-setup.sh)"}},
	},
	"LokiInstance": {
		"*": {{CRD: "releases.helm.m.crossplane.io", Hint: "install provider-helm (Hiroba scripts/e2e-setup.sh)"}},
	},
	"PrometheusInstance": {
		"*": {{CRD: "releases.helm.m.crossplane.io", Hint: "install provider-helm (Hiroba scripts/e2e-setup.sh)"}},
	},
	"MimirInstance": {
		"*": {{CRD: "releases.helm.m.crossplane.io", Hint: "install provider-helm (Hiroba scripts/e2e-setup.sh)"}},
	},
	"AlloyInstance": {
		"*": {{CRD: "releases.helm.m.crossplane.io", Hint: "install provider-helm (Hiroba scripts/e2e-setup.sh)"}},
	},
}

// RequiredDependencies returns the CRDs required for the given XR kind and
// provider: the union of the wildcard ("*") and provider-specific entries.
func RequiredDependencies(kind, provider string) []Dependency {
	byProvider, ok := Dependencies[kind]
	if !ok {
		return nil
	}
	out := append([]Dependency{}, byProvider["*"]...)
	out = append(out, byProvider[provider]...)
	return out
}
