// Code generated by scripts/gen-contract.ts from contract/contract.json. DO NOT EDIT.

package contract

const APIGroup = "platform.7kgroup.org"
const APIVersion = "v1alpha1"
const APIGroupVersion = "platform.7kgroup.org/v1alpha1"
const OrchestratorFunctionName = "function-platform"

const (
	LabelTeam       = "team"
	LabelCostCenter = "cost-center"
	LabelStack      = "platform.7kgroup.org/stack"
)

// ProfileDefaults holds the per-profile infrastructure defaults applied by
// handlers when the XR spec does not override them.
type ProfileDefaults struct {
	InstanceClass       string
	MultiAZ             bool
	BackupRetentionDays int64
	DeletionProtection  bool
	StorageEncrypted    bool
	DeletionPolicy      string
}

var Profiles = map[string]ProfileDefaults{
	"development": {InstanceClass: "db.t3.micro", MultiAZ: false, BackupRetentionDays: 1, DeletionProtection: false, StorageEncrypted: false, DeletionPolicy: "Delete"},
	"staging":     {InstanceClass: "db.t3.small", MultiAZ: false, BackupRetentionDays: 7, DeletionProtection: false, StorageEncrypted: true, DeletionPolicy: "Delete"},
	"production":  {InstanceClass: "db.r6g.xlarge", MultiAZ: true, BackupRetentionDays: 30, DeletionProtection: true, StorageEncrypted: true, DeletionPolicy: "Orphan"},
}

var ProfileNames = []string{"development", "staging", "production"}

var PostgresProviders = []string{"aws", "cnpg"}

const PostgresDefaultProvider = "cnpg"
const PostgresDefaultRegion = "us-east-1"

var PostgresConnectionKeys = []string{"host", "port", "username", "password", "database", "uri"}

var ObjectStorageProviders = []string{"s3", "garage"}

const ObjectStorageDefaultProvider = "garage"
const ObjectStorageDefaultRegion = "us-east-1"

var ObjectStorageConnectionKeys = []string{"endpoint", "bucket", "region", "accessKeyId", "secretAccessKey", "uri"}
