name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: 7KGroup/workflow-library/.github/workflows/release.yml@v1
    with:
      image-name: ghcr.io/7kgroup/${{ values.name }}
    secrets: inherit

  publish-chart:
    needs: release
    uses: 7KGroup/workflow-library/.github/workflows/helm-publish.yml@v1
    with:
      chart-path: helm/base
    secrets: inherit
