apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-platform-aggregate
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: 'true'
rules:
  - apiGroups: ['platform.yourcompany.io']
    resources:
      - 'grafanainstances'
      - 'lokiinstances'
      - 'prometheusinstances'
    verbs: ['*']
