apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-admin
rules:
  - apiGroups: ['platform.7kgroup.org']
    resources: ['*']
    verbs: ['*']
  - apiGroups: ['apiextensions.crossplane.io']
    resources: ['compositions', 'compositeresourcedefinitions']
    verbs: ['*']
