// Code generated by scripts/gen-contract.ts from contract/contract.json. DO NOT EDIT.

export const API_GROUP = 'platform.7kgroup.org';
export const API_VERSION = 'v1alpha1';
export const API_GROUP_VERSION = 'platform.7kgroup.org/v1alpha1';
export const ORCHESTRATOR_FUNCTION_NAME = 'function-platform';

export const PLATFORM_LABELS = {
  "team": "team",
  "costCenter": "cost-center",
  "stack": "platform.7kgroup.org/stack"
} as const;

export type Profile = 'development' | 'staging' | 'production';
export const PROFILES: Profile[] = ['development', 'staging', 'production'];

export interface ProfileDefaults {
  readonly instanceClass: string;
  readonly multiAZ: boolean;
  readonly backupRetentionDays: number;
  readonly deletionProtection: boolean;
  readonly storageEncrypted: boolean;
  readonly deletionPolicy: 'Delete' | 'Orphan';
}

export const PROFILE_DEFAULTS: Record<Profile, ProfileDefaults> = {
  "development": {
    "instanceClass": "db.t3.micro",
    "multiAZ": false,
    "backupRetentionDays": 1,
    "deletionProtection": false,
    "storageEncrypted": false,
    "deletionPolicy": "Delete"
  },
  "staging": {
    "instanceClass": "db.t3.small",
    "multiAZ": false,
    "backupRetentionDays": 7,
    "deletionProtection": false,
    "storageEncrypted": true,
    "deletionPolicy": "Delete"
  },
  "production": {
    "instanceClass": "db.r6g.xlarge",
    "multiAZ": true,
    "backupRetentionDays": 30,
    "deletionProtection": true,
    "storageEncrypted": true,
    "deletionPolicy": "Orphan"
  }
};

export interface ProductContract {
  readonly kind: string;
  readonly plural: string;
  readonly singular: string;
  readonly providers: readonly string[];
  readonly defaultProvider: string;
  readonly defaultRegion?: string;
  readonly connectionKeys: readonly string[];
}

export const PRODUCT_CONTRACTS = {
  "postgres": {
    "kind": "PostgresInstance",
    "plural": "postgresinstances",
    "singular": "postgresinstance",
    "providers": [
      "aws",
      "cnpg"
    ],
    "defaultProvider": "cnpg",
    "defaultRegion": "us-east-1",
    "connectionKeys": [
      "host",
      "port",
      "username",
      "password",
      "database",
      "uri"
    ]
  },
  "objectStorage": {
    "kind": "ObjectBucket",
    "plural": "objectbuckets",
    "singular": "objectbucket",
    "providers": [
      "s3",
      "garage"
    ],
    "defaultProvider": "garage",
    "defaultRegion": "us-east-1",
    "connectionKeys": [
      "endpoint",
      "bucket",
      "region",
      "accessKeyId",
      "secretAccessKey",
      "uri"
    ]
  }
} as const satisfies Record<string, ProductContract>;

export const POSTGRES_PROVIDERS = ["aws","cnpg"] as const;
export const POSTGRES_CONNECTION_KEYS = ["host","port","username","password","database","uri"] as const;

export const OBJECT_STORAGE_PROVIDERS = ["s3","garage"] as const;
export const OBJECT_STORAGE_CONNECTION_KEYS = ["endpoint","bucket","region","accessKeyId","secretAccessKey","uri"] as const;

export interface Dependency {
  readonly crd: string;
  readonly hint: string;
}

/** Required CRDs per XR kind and provider ("*" = all providers). */
export const DEPENDENCIES = {
  "PostgresInstance": {
    "cnpg": [
      {
        "crd": "clusters.postgresql.cnpg.io",
        "hint": "install the CloudNativePG operator: helm upgrade --install cnpg cnpg/cloudnative-pg -n cnpg-system --create-namespace"
      }
    ],
    "aws": [
      {
        "crd": "instances.rds.aws.m.upbound.io",
        "hint": "install provider-aws-rds: kubectl apply -f infrastructure/crossplane-control-plane/providers.yaml"
      }
    ]
  },
  "ObjectBucket": {
    "garage": [
      {
        "crd": "garagebuckets.garage.rajsingh.info",
        "hint": "install the Garage operator (garage.rajsingh.info)"
      }
    ],
    "s3": [
      {
        "crd": "buckets.s3.aws.m.upbound.io",
        "hint": "install provider-aws-s3: kubectl apply -f infrastructure/crossplane-control-plane/providers.yaml"
      }
    ]
  },
  "GrafanaInstance": {
    "*": [
      {
        "crd": "releases.helm.m.crossplane.io",
        "hint": "install provider-helm (Hiroba scripts/e2e-setup.sh) and a namespaced <team>-helm ProviderConfig (scripts/team-setup.sh)"
      }
    ]
  },
  "LokiInstance": {
    "*": [
      {
        "crd": "releases.helm.m.crossplane.io",
        "hint": "install provider-helm (Hiroba scripts/e2e-setup.sh)"
      }
    ]
  },
  "PrometheusInstance": {
    "*": [
      {
        "crd": "releases.helm.m.crossplane.io",
        "hint": "install provider-helm (Hiroba scripts/e2e-setup.sh)"
      }
    ]
  },
  "MimirInstance": {
    "*": [
      {
        "crd": "releases.helm.m.crossplane.io",
        "hint": "install provider-helm (Hiroba scripts/e2e-setup.sh)"
      }
    ]
  },
  "AlloyInstance": {
    "*": [
      {
        "crd": "releases.helm.m.crossplane.io",
        "hint": "install provider-helm (Hiroba scripts/e2e-setup.sh)"
      }
    ]
  }
} as const satisfies Record<string, Record<string, readonly Dependency[]>>;
