apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates
  description: Collection of all Backstage templates
spec:
  targets:
    - ./app-template/template.yaml
    - ./stack-template/template.yaml
