apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ${{ values.name }}
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: okura
spec:
  interval: 5m
  url: https://github.com/7K-Okura/${{ values.name }}.git
  ref:
    branch: main
