/**
 * Code generator for the platform contract.
 *
 * Reads contract/contract.json (the single source of truth for API versions,
 * profiles, provider vocabularies and connection-secret contracts) and emits:
 *   - packages/shared/src/contract.gen.ts
 *   - functions/platform/internal/contract/contract.gen.go
 *
 * Usage: npx ts-node scripts/gen-contract.ts [--check]
 *   --check  Regenerate and fail if the committed output is stale.
 */
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

interface ProfileDefaults {
  instanceClass: string;
  multiAZ: boolean;
  backupRetentionDays: number;
  deletionProtection: boolean;
  storageEncrypted: boolean;
  deletionPolicy: 'Delete' | 'Orphan';
}

interface ProductContract {
  kind: string;
  plural: string;
  singular: string;
  providers: string[];
  defaultProvider: string;
  defaultRegion?: string;
  connectionKeys: string[];
}

interface Dependency {
  crd: string;
  hint: string;
}

interface Contract {
  apiGroup: string;
  apiVersion: string;
  orchestratorFunction: string;
  labels: { team: string; costCenter: string; stack: string };
  profiles: Record<string, ProfileDefaults>;
  products: Record<string, ProductContract>;
  dependencies?: Record<string, Record<string, Dependency[]>>;
}

const REPO_ROOT = path.resolve(__dirname, '..');
const CONTRACT_PATH = path.join(REPO_ROOT, 'contract', 'contract.json');
const TS_OUT = path.join(REPO_ROOT, 'packages', 'shared', 'src', 'contract.gen.ts');
const GO_OUT = path.join(REPO_ROOT, 'functions', 'platform', 'internal', 'contract', 'contract.gen.go');

const GENERATED_HEADER = '// Code generated by scripts/gen-contract.ts from contract/contract.json. DO NOT EDIT.';

function loadContract(): Contract {
  return JSON.parse(fs.readFileSync(CONTRACT_PATH, 'utf-8')) as Contract;
}

function renderTs(c: Contract): string {
  const profileNames = Object.keys(c.profiles);
  const lines: string[] = [
    GENERATED_HEADER,
    '',
    `export const API_GROUP = '${c.apiGroup}';`,
    `export const API_VERSION = '${c.apiVersion}';`,
    `export const API_GROUP_VERSION = '${c.apiGroup}/${c.apiVersion}';`,
    `export const ORCHESTRATOR_FUNCTION_NAME = '${c.orchestratorFunction}';`,
    '',
    `export const PLATFORM_LABELS = ${JSON.stringify(c.labels, null, 2)} as const;`,
    '',
    `export type Profile = ${profileNames.map((p) => `'${p}'`).join(' | ')};`,
    `export const PROFILES: Profile[] = [${profileNames.map((p) => `'${p}'`).join(', ')}];`,
    '',
    'export interface ProfileDefaults {',
    '  readonly instanceClass: string;',
    '  readonly multiAZ: boolean;',
    '  readonly backupRetentionDays: number;',
    '  readonly deletionProtection: boolean;',
    '  readonly storageEncrypted: boolean;',
    "  readonly deletionPolicy: 'Delete' | 'Orphan';",
    '}',
    '',
    `export const PROFILE_DEFAULTS: Record<Profile, ProfileDefaults> = ${JSON.stringify(c.profiles, null, 2)};`,
    '',
    'export interface ProductContract {',
    '  readonly kind: string;',
    '  readonly plural: string;',
    '  readonly singular: string;',
    '  readonly providers: readonly string[];',
    '  readonly defaultProvider: string;',
    '  readonly defaultRegion?: string;',
    '  readonly connectionKeys: readonly string[];',
    '}',
    '',
    `export const PRODUCT_CONTRACTS = ${JSON.stringify(c.products, null, 2)} as const satisfies Record<string, ProductContract>;`,
    '',
  ];

  for (const [name, product] of Object.entries(c.products)) {
    const constName = name.replace(/([A-Z])/g, '_$1').toUpperCase();
    lines.push(
      `export const ${constName}_PROVIDERS = ${JSON.stringify(product.providers)} as const;`,
      `export const ${constName}_CONNECTION_KEYS = ${JSON.stringify(product.connectionKeys)} as const;`,
      '',
    );
  }

  lines.push(
    'export interface Dependency {',
    '  readonly crd: string;',
    '  readonly hint: string;',
    '}',
    '',
    '/** Required CRDs per XR kind and provider ("*" = all providers). */',
    `export const DEPENDENCIES = ${JSON.stringify(c.dependencies ?? {}, null, 2)} as const satisfies Record<string, Record<string, readonly Dependency[]>>;`,
    '',
  );

  return lines.join('\n');
}

function goStringSlice(values: string[]): string {
  return `[]string{${values.map((v) => JSON.stringify(v)).join(', ')}}`;
}

function renderGo(c: Contract): string {
  const profileNames = Object.keys(c.profiles);
  const lines: string[] = [
    GENERATED_HEADER,
    '',
    'package contract',
    '',
    `const APIGroup = ${JSON.stringify(c.apiGroup)}`,
    `const APIVersion = ${JSON.stringify(c.apiVersion)}`,
    `const APIGroupVersion = ${JSON.stringify(c.apiGroup + '/' + c.apiVersion)}`,
    `const OrchestratorFunctionName = ${JSON.stringify(c.orchestratorFunction)}`,
    '',
    'const (',
    `\tLabelTeam       = ${JSON.stringify(c.labels.team)}`,
    `\tLabelCostCenter = ${JSON.stringify(c.labels.costCenter)}`,
    `\tLabelStack      = ${JSON.stringify(c.labels.stack)}`,
    ')',
    '',
    '// ProfileDefaults holds the per-profile infrastructure defaults applied by',
    '// handlers when the XR spec does not override them.',
    'type ProfileDefaults struct {',
    '\tInstanceClass       string',
    '\tMultiAZ             bool',
    '\tBackupRetentionDays int64',
    '\tDeletionProtection  bool',
    '\tStorageEncrypted    bool',
    '\tDeletionPolicy      string',
    '}',
    '',
    'var Profiles = map[string]ProfileDefaults{',
  ];

  for (const [name, p] of Object.entries(c.profiles)) {
    lines.push(
      `\t${JSON.stringify(name)}: {` +
        `InstanceClass: ${JSON.stringify(p.instanceClass)}, ` +
        `MultiAZ: ${p.multiAZ}, ` +
        `BackupRetentionDays: ${p.backupRetentionDays}, ` +
        `DeletionProtection: ${p.deletionProtection}, ` +
        `StorageEncrypted: ${p.storageEncrypted}, ` +
        `DeletionPolicy: ${JSON.stringify(p.deletionPolicy)}},`,
    );
  }

  lines.push('}', '', `var ProfileNames = ${goStringSlice(profileNames)}`, '');

  for (const [name, product] of Object.entries(c.products)) {
    const exported = name
      .split(/(?=[A-Z])/)
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join('');
    lines.push(
      `var ${exported}Providers = ${goStringSlice(product.providers)}`,
      `const ${exported}DefaultProvider = ${JSON.stringify(product.defaultProvider)}`,
    );
    if (product.defaultRegion) {
      lines.push(`const ${exported}DefaultRegion = ${JSON.stringify(product.defaultRegion)}`);
    }
    lines.push(`var ${exported}ConnectionKeys = ${goStringSlice(product.connectionKeys)}`, '');
  }

  lines.push(
    '// ProductByKind maps an XR kind to its contract product key.',
    'var ProductByKind = map[string]string{',
  );
  for (const [name, product] of Object.entries(c.products)) {
    lines.push(`\t${JSON.stringify(product.kind)}: ${JSON.stringify(name)},`);
  }
  lines.push('}', '');

  lines.push(
    '// DefaultProviderByKind maps an XR kind to its contract default provider.',
    'var DefaultProviderByKind = map[string]string{',
  );
  for (const [, product] of Object.entries(c.products)) {
    lines.push(`\t${JSON.stringify(product.kind)}: ${JSON.stringify(product.defaultProvider)},`);
  }
  lines.push('}', '');

  lines.push(
    '// Dependency is a CRD that must be installed before the given XR kind can be',
    '// reconciled, plus an actionable install hint surfaced to the client.',
    'type Dependency struct {',
    '\tCRD  string',
    '\tHint string',
    '}',
    '',
    '// Dependencies maps XR kind -> provider ("*" = all providers) -> required CRDs.',
    'var Dependencies = map[string]map[string][]Dependency{',
  );
  for (const [kind, byProvider] of Object.entries(c.dependencies ?? {})) {
    lines.push(`\t${JSON.stringify(kind)}: {`);
    for (const [provider, deps] of Object.entries(byProvider)) {
      const items = deps.map((d) => `{CRD: ${JSON.stringify(d.crd)}, Hint: ${JSON.stringify(d.hint)}}`).join(', ');
      lines.push(`\t\t${JSON.stringify(provider)}: {${items}},`);
    }
    lines.push('\t},');
  }
  lines.push('}', '');

  lines.push(
    '// RequiredDependencies returns the CRDs required for the given XR kind and',
    '// provider: the union of the wildcard ("*") and provider-specific entries.',
    'func RequiredDependencies(kind, provider string) []Dependency {',
    '\tbyProvider, ok := Dependencies[kind]',
    '\tif !ok {',
    '\t\treturn nil',
    '\t}',
    '\tout := append([]Dependency{}, byProvider["*"]...)',
    '\tout = append(out, byProvider[provider]...)',
    '\treturn out',
    '}',
    '',
  );

  return lines.join('\n');
}

function main(): void {
  const check = process.argv.includes('--check');
  const contract = loadContract();
  const outputs: Array<[string, string]> = [
    [TS_OUT, renderTs(contract)],
    // gofmt the Go output so committed code matches gofmt'ed trees.
    [GO_OUT, execSync('gofmt', { input: renderGo(contract), encoding: 'utf-8' })],
  ];

  let stale = false;
  for (const [file, content] of outputs) {
    const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf-8') : '';
    if (existing !== content) {
      if (check) {
        console.error(`STALE: ${path.relative(REPO_ROOT, file)} — run 'npm run gen:contract'`);
        stale = true;
      } else {
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, content);
        console.log(`wrote ${path.relative(REPO_ROOT, file)}`);
      }
    }
  }

  if (check) {
    if (stale) process.exit(1);
    console.log('contract codegen output is up to date');
    return;
  }

  try {
    execSync(`gofmt -w ${GO_OUT}`, { stdio: 'inherit' });
  } catch {
    console.warn('gofmt not available; skipping Go formatting');
  }
}

main();
