/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    'mission',
    'roadmap',
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/overview',
        'architecture/base-vs-platform',
        'architecture/backstage-templates',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/getting-started',
        'guides/using-helm-templates',
        'guides/containerization',
        'guides/crossplane-compositions',
      ],
    },
    {
      type: 'category',
      label: 'Apps',
      link: {
        type: 'generated-index',
        title: 'App Documentation',
        description: 'Documentation for applications built with Hiroba templates.',
        slug: '/apps',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'apps',
        },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        'community/contributing',
        'community/governance',
      ],
    },
  ],
};

module.exports = sidebars;
