apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-deletion-policy
spec:
  rules:
    - name: check-deletion-policy
      match:
        resources:
          kinds:
            - platform.7kgroup.org/v1/PostgreSQLInstance
      validate:
        message: "Production databases must have deletionPolicy: Orphan"
        pattern:
          spec:
            deletionPolicy: "Orphan"
