apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-cost-center
spec:
  validationFailureAction: Enforce
  rules:
    - name: check-cost-center
      match:
        resources:
          kinds:
            - platform.7kgroup.org/v1/ObservabilityStack
      validate:
        message: "ObservabilityStack must have spec.costCenter"
        pattern:
          spec:
            costCenter: "?*"
