name: Helm libraries CI

on:
  pull_request:
    branches: [main]
    paths:
      - "helm/lib/**"
      - ".github/workflows/charts-ci.yml"

permissions:
  contents: write

jobs:
  app-lib:
    uses: 7K-Hiroba/workflows-library/.github/workflows/ci-helm-library.yml@v1
    with:
      path: helm/lib/app

  platform-lib:
    uses: 7K-Hiroba/workflows-library/.github/workflows/ci-helm-library.yml@v1
    with:
      path: helm/lib/platform
  
  helm-docs:
    uses: 7K-Hiroba/workflows-library/.github/workflows/ci-helm-docs.yml@v1
